### ISSUE TITLE
Request for two new instances to replace FWSPublic and FWS Primary

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/swi#182]
Requesting images with latest ArcGIS Server at same type and size as current machines. Requesting fresh new (no data) EBS volume attached as E: at same specs as E: drive attached to current machines.

**Comment by njestes** [comment]
@aaronstephenson @fanguyc-usgs curious about the progress on this one. We are hoping to have these fully configured and ready to replace the current FWS machines in May. Early May, I believe, but I can get a more precise date from someone at FWS.

**Comment by aaronstephenson** [comment]
We emailed Zivaro to ask about this and say we want those two instances launched. They will do it but said we don't have enough funds right now. Hans and Lorraine are trying to make those funds available but they're currently being reviewed somewhere up the bureaucratic chain.

**Comment by aaronstephenson** [comment]
Just following up on this... we met with FWS folks on June 9 and decided to continue using the current EC2 instances and not launch new ones, since the current instances have not been very troublesome the last few months and the estimate from Zivaro was far more than we expected. Next year as we approach the end of the current Reserved Instance period (April 20, 2022) we will reassess.
